"""Add LinkedIn token fields to user model

Revision ID: 1951227b6fee
Revises: 4df3c9ea9688
Create Date: 2025-08-03 11:20:17.119009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1951227b6fee'
down_revision: Union[str, None] = '4df3c9ea9688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Drop user table if exists
    op.drop_table('user')

    # Re-create user table
    op.create_table(
        'user',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('username', sa.String, unique=True, index=True, nullable=False),
        sa.Column('hashed_password', sa.String, nullable=False),
        sa.Column('li_access_token', sa.String, nullable=True),
        sa.Column('li_refresh_token', sa.String, nullable=True),
        sa.Column('li_expires_at', sa.Float, nullable=True),
        sa.Column('li_owner_urn', sa.String, nullable=True),
        # add any other columns that your model has
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'li_owner_urn')
    op.drop_column('users', 'li_expires_at')
    op.drop_column('users', 'li_refresh_token')
    op.drop_column('users', 'li_access_token')
    # ### end Alembic commands ###
