"""Add image_url to planned_posts

Revision ID: 3d7cad4f8b88
Revises: 4df3c9ea9688
Create Date: 2025-08-03 14:58:24.558282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7cad4f8b88'
down_revision: Union[str, None] = '4df3c9ea9688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_posts', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_posts', 'image_url')
    # ### end Alembic commands ###
