"""Add image_url to planned_posts

Revision ID: 6e1fbe2ea846
Revises: 3d7cad4f8b88
Create Date: 2025-08-03 15:06:02.378647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1fbe2ea846'
down_revision: Union[str, None] = '3d7cad4f8b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("planned_posts", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
